server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schedulemanage?serverTimezone=GMT%2b8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
mybatis:
  mapper-locations: classpath:mapper/*.xml

files:
  upload:
    path: D:/IDEAProject/files/

